version: "3.7"
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: inz
    networks:
      - backend
  api_service:
    build: .
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080"
    container_name: 'the_new_container_name'
    environment:
      spring.datasource.url: "jdbc:mysql://db:3306/inz?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"



networks:
  backend:

